services:
  - node:11.2.0

stages:
  - build
  - test
  - deploy

install_dependecies:
  tags:
    - devops
    - docker
  only:
    - master
  stage: build
  script:
    - npm -v
    - node -v
    - npm install

run_tests:
  only:
    - master
  stage: test
  script:
    - npm run lint
    - npm run test

deploy_bundle:
  only:
    - master
  stage: deploy
  before_script:
    - npm -v
    - node -v
    - npm install
    - npm run lint
    - npm run test
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - npm run build
